<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Wisegar.DTXInspector.App'">
    <DTXInspectorDesktopProject>true</DTXInspectorDesktopProject>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
</Project>
