<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DtxNodeCheck.Workstation</AssemblyName>
    <ApplicationManifest>..\DtxNodeCheck\app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DtxNodeCheck.Core\DtxNodeCheck.Core.csproj" />
    <Compile Include="..\DtxNodeCheck.Desktop.Shared\*.cs" Link="Desktop\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
